name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Make application.properties
      run: |
        mkdir ./src/main/resources
        touch ./src/main/resources/application.properties
        echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties

      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew clean build
        
      
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-test .

    - name: docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-test


  deploy :
    needs: build
    runs-on: self-hosted

    steps:
      - name: docker pull
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-test
      
      - name: docker stop container
        run: sudo docker stop $(sudo docker ps -q) 2>/dev/null || true

      - name: docker run new container
        run: sudo docker run --name github-actions-test --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-test

      - name: delete old docker image
        run: sudo docker system prune -f
